### ISSUE TITLE
Bug when using crop_n_layers > 0

### ISSUE THREAD

**Issue by ilan-theodoro** [ymgw55/segment-anything-edge-detection#1]
The error happens when the `MaskData` object tries to concatenate the probability maps `crop_data["probs"]` from different crop sizes, which eventually leads to dimension mismatch. 

```python
# Iterate over image crops
data = MaskData()
for crop_box, layer_idx in zip(crop_boxes, layer_idxs):
    crop_data = self._process_crop(image, crop_box, layer_idx, orig_size)
    data.cat(crop_data)
```

**Comment by ymgw55** [comment]
Thank you.

Probably, when performing edge detection in the paper, it was not assumed that `crop_n_layers` > 0, so I did'nt confirm it myself. I might not be able to check it right away, but when I have time, I'll look at the code and if there are no problems, I plan to merge it.

**Comment by ilan-theodoro** [comment]
I see. Well, that option might be good. I'm trying different parameters for my application.
