### ISSUE TITLE
IoU and Stability Score filtering disabled

### ISSUE THREAD

**Issue by ilan-theodoro** [ymgw55/segment-anything-edge-detection#3]
Hi, I see that you disabled edge and stability score filtering. 

https://github.com/ymgw55/segment-anything-edge-detection/blob/2d2f8cee86cc43f54a08a524d6efb265c210615b/automatic_mask_and_probability_generator.py#L306

https://github.com/ymgw55/segment-anything-edge-detection/blob/2d2f8cee86cc43f54a08a524d6efb265c210615b/automatic_mask_and_probability_generator.py#L315

But I'm using for an application of cell edge detection where objects are sparsely distributed along the image, and if I don't filter the edge map looks like this:

![image](https://github.com/ymgw55/segment-anything-edge-detection/assets/7650238/e0577d42-9eac-491a-ba9c-2be2150da425)

I understand why the filtering should be disabled in most applications, but I think that could be an option for the user.

**Comment by ymgw55** [comment]
@ilan-theodoro
Hi, I added arguments for `pred_iou_thresh` and `stability_score_thresh`. If these values are positive, you can add the filterings.

**Comment by ymgw55** [comment]
Sorry, I changed arguments. Please use `--pred_iou_thresh_filtering` or `--stability_score_thresh_filtering`.
