### ISSUE TITLE
CUDA out of memory Error

### ISSUE THREAD

**Issue by itsarakio** [ymgw55/segment-anything-edge-detection#7]
@ymgw55

hello first of all thank you for implement this reposetory,

`generator = SamAutomaticMaskAndProbabilityGenerator(sam)`

I got this error please someone help me what should i have to do ? 
RuntimeError: CUDA out of memory. Tried to allocate 1024.00 MiB (GPU 0; 2.00 GiB total capacity; 4.60 GiB already allocated; 0 bytes free; 4.67 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by ymgw55** [comment]
@theamircodex 
Thank you for using my code. Please try running on a GPU with more memory.
